sudo: required
services:
    - docker

before_install:
    - docker build -t vaibhavgulhane/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vaibhavgulhane/docker-react npm run test